//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliRunner.Specializations.Internal.Localizations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CliRunner.Specializations.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Exceptions_ClassicPowershell_OnlySupportedOnWindows {
            get {
                return ResourceManager.GetString("Exceptions.ClassicPowershell.OnlySupportedOnWindows", resourceCulture);
            }
        }
        
        internal static string Exceptions_Cmd_OnlySupportedOnWindows {
            get {
                return ResourceManager.GetString("Exceptions.Cmd.OnlySupportedOnWindows", resourceCulture);
            }
        }
        
        internal static string Exceptions_Cmd_NotInstalled {
            get {
                return ResourceManager.GetString("Exceptions.Cmd.NotInstalled", resourceCulture);
            }
        }
        
        internal static string Exceptions_ClassicPowershell_NotInstalled {
            get {
                return ResourceManager.GetString("Exceptions.ClassicPowershell.NotInstalled", resourceCulture);
            }
        }
        
        internal static string Exceptions_Powershell_VersionNotFound {
            get {
                return ResourceManager.GetString("Exceptions.Powershell.VersionNotFound", resourceCulture);
            }
        }
        
        internal static string Exceptions_Powershell_NotInstalled {
            get {
                return ResourceManager.GetString("Exceptions.Powershell.NotInstalled", resourceCulture);
            }
        }
        
        internal static string Exceptions_Powershell_OnlySupportedOnDesktop {
            get {
                return ResourceManager.GetString("Exceptions.Powershell.OnlySupportedOnDesktop", resourceCulture);
            }
        }
    }
}
