//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlastairLundy.CliInvoke.Specializations.Internal.Localizations {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CliInvoke.Specializations.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powershell.exe is not installed on this system. This may be because you are running a non-windows operating system..
        /// </summary>
        internal static string Exceptions_ClassicPowershell_NotInstalled {
            get {
                return ResourceManager.GetString("Exceptions.ClassicPowershell.NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsPowerShell is not supproted on Operating Systems that are not based on Windows..
        /// </summary>
        internal static string Exceptions_ClassicPowershell_OnlySupportedOnWindows {
            get {
                return ResourceManager.GetString("Exceptions.ClassicPowershell.OnlySupportedOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmd.exe is not installed on this system. This may be because you are running a non-windows operating system..
        /// </summary>
        internal static string Exceptions_Cmd_NotInstalled {
            get {
                return ResourceManager.GetString("Exceptions.Cmd.NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmd is not supported on Operating systems that are not based on Windows..
        /// </summary>
        internal static string Exceptions_Cmd_OnlySupportedOnWindows {
            get {
                return ResourceManager.GetString("Exceptions.Cmd.OnlySupportedOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell is not installed on this system..
        /// </summary>
        internal static string Exceptions_Powershell_NotInstalled {
            get {
                return ResourceManager.GetString("Exceptions.Powershell.NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell only supports Windows, macOS, Linux, and FreeBSD..
        /// </summary>
        internal static string Exceptions_Powershell_OnlySupportedOnDesktop {
            get {
                return ResourceManager.GetString("Exceptions.Powershell.OnlySupportedOnDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detect the version of Powershell installed on this system. This could be because Powershell (Classic or Modern) is not installed on this device..
        /// </summary>
        internal static string Exceptions_Powershell_VersionNotFound {
            get {
                return ResourceManager.GetString("Exceptions.Powershell.VersionNotFound", resourceCulture);
            }
        }
    }
}
